### ISSUE TITLE
Authors should be able to merge PRs not changing the status

### ISSUE THREAD

**Issue by sullof** [ethereum/ERCs#149]
### Pull Request

https://github.com/ethereum/ERCs/pull/123

### What happened?

In this PR I just updated the comments in the interface to clarify some doubts raised by the community. According to the rules, I should be able to merge it without requiring an intervention by one of the editors. However, neither me nor my co-author have that possibility. It looks to me like a bug

**Comment by SamWilsn** [comment]
Have you seen this recently? I believe I fixed it with https://github.com/ethereum/eip-review-bot/commit/2340122a819a3ff0fcb52e428bb7e8b65405e260
