### ISSUE TITLE
Add support for rendering interfaces in multiple languages when YAML ABIs are used in ERCs

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/ERCs#24]
A suggestion per [EIP-2069](https://eips.ethereum.org/EIPS/eip-2069) (which should be taken up as a separate issue to migrate existing ERCs to this standard) is to write ABIs for ERC interfaces in a YAML format (for example, [ERC-4626](https://eips.ethereum.org/EIPS/eip-4626))

There are lots of benefits of this (can lint ABI interfaces, can directly lift them into external tools, use them directly within different languages, host an ERCs package, etc) but a really big benefit is that we can easily render these interfaces into different smart contract languages when providing examples

So, someone reading up on ERC4626 can click a button and see all the examples in Solidity or Vyper (or other languages such as Huff, Fe, etc), or even as JS/Python/Rust objects and import them easily with how they would like to use it

Suggesting or enforcing YAML ABIs also has the side benefit of ensuring that an ERC is well formed,  and not prescriptive of particular language features

**Comment by lightclient** [comment]
Wrong button. I think this is a good idea. What do you think @xinbenlv ?
