### ISSUE TITLE
Pull request stuck at "Merging can be performed automatically with 0 approving reviews" 

### ISSUE THREAD

**Issue by henrywfyeung** [ethereum/ERCs#334]
### Pull Request

https://github.com/ethereum/ERCs/pull/221

### What happened?

I submitted a request on Jan 26. It was a migration from the EIP repository to ERC. This pull request (221) was stuck at the error "Merging can be performed automatically with 0 approving reviews" with no further attention. It seems that the EIP bot should automatically merge the pull request, but it didn't happen. Can someone please advise on how we can proceed from here?

**Comment by iunknow588** [comment]
This seems to be that further discussion and development are needed,  the owner or community members need to continue discussing and let the idea ferment for a while.

**Comment by abcoathup** [comment]
You need to wait for an ERC editor to review.  
You could try raising in the EIP editing office hour meeting: https://github.com/ethcatherders/EIPIP/issues/330

**Comment by SamWilsn** [comment]
Yeah, this isn't a bug. This is just Editors taking ages to review things. Sorry, we'll get to it when we can!
