### ISSUE TITLE
Jekyll jobs have been failing for two weeks now

### ISSUE THREAD

**Issue by alcueca** [ethereum/ERCs#558]
### Pull Request

https://github.com/ethereum/ERCs/pull/500

### What happened?

CI fails in all PRs for the last two weeks.

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/3fd16fb7-e7ab-49e7-959d-f53a321e2fbb">

**Comment by SamWilsn** [comment]
Should be working now.
