### ISSUE TITLE
Migrating Pull Requests from `ethereum/EIPs` to `ethereum/ERCs`

### ISSUE THREAD

**Issue by lightclient** [ethereum/ERCs#8]
If you are trying to move a PR you made to `ethereum/eips` over to `ethereum/ercs`, the steps below will guide you through the process:

1. Fork this repository within GitHub:
    1. Navigate to [ethereum/ERCs](https://github.com/ethereum/ERCs).
    1. Find the "Fork" button in the upper right side of the screen and click it.
    1. Proceed with repository creation.

2. Clone your fork locally:
    1. `git clone https://github.com/{user}/ercs`

3. Enter the newly created `ercs` folder:
    1. `cd ercs`

4. Add your fork of the EIPs repository as a remote:
    1. `git remote add eips https://github.com/{user}/eips`

5. Fetch that remote to download your branches:
    1. `git fetch eips`

6. Now checkout the branch related to your original PR:
    1. `git checkout {branch}`

7. Rebase your branch against the ERCs repo:
    1. `git rebase master`
    2. Please note, you do not need to update any references of EIP to ERC; particularly in the relative links. Even though `[ERC-X](./eip-x.md)` doesn't correctly render in this repository, we're currently building the full `eips.ethereum.org` still in the `ethereum/eips` repository. So until we resolve this in #1, we will continue using this relative linking format.

8. Push your branch to your ERCs fork:
    1. `git push -u origin {branch}`

9. Now you can recreate your pull request:
    1. Navigate to https://github.com/ethereum/ERCs/compare
    3. Select your newly created fork and branch
    4. open a new PR to this repo.

Additional notes:

- Do NOT link to ERCs using their filename. Link to ERCs using `[ERC-XXXX](./eip-XXXX.md)`.

**Comment by zakrad** [comment]
> If you are trying to move a PR you made to `ethereum/eips` over to `ethereum/ercs`, the steps below will guide you through the process:
> 
>     1. Fork this repository within GitHub:
>        
>        1. Navigate to [ethereum/ERCs](https://github.com/ethereum/ERCs).
>        2. Find the "Fork" button in the upper right side of the screen and click it.
>        3. Proceed with repository creation.
> 
>     2. Clone your fork locally:
>        
>        1. `git clone https://github.com/{user}/ercs`
> 
>     3. Enter the newly created `ercs` folder:
>        
>        1. `cd ercs`
> 
>     4. Add your fork of the EIPs repository as a remote:
>        
>        1. `git add remote eips https://github.com/{user}/eips`
> 
>     5. Fetch that remote to download your branches:
>        
>        1. `git fetch eips`
> 
>     6. Now checkout the branch related to your original PR:
>        
>        1. `git checkout {branch}`
> 
>     7. Rebase your branch against the ERCs repo:
>        
>        1. `git rebase master`
> 
>     8. Push your branch to your ERCs fork:
>        
>        1. `git push -u origin {branch}`
> 
>     9. Now you can recreate your pull request:
>        
>        1. Navigate to https://github.com/ethereum/ERCs/compare
>        2. Select your newly created fork and branch
>        3. open a new PR to this repo.

Its `git remote add eips https://github.com/{user}/eips` not `git add remote eips https://github.com/{user}/eips`

**Comment by cfries** [comment]
Step number 7 will likely create conflicts because the folders inside assets have been renamed from eip-NNNN to erc-NNNN. Isn't it?

**Comment by sullof** [comment]
It looks like even doing a little changes produces a lot of errors because of all the references in the documents about `./eip-...` documents. A script replacing any `./eip-` reference to a `./erc-` reference would solve the problem as soon as anyone merges the fix.

**Comment by TtheBC01** [comment]
I think in step 4 of your instructions you need to flip `remote` and `add` around

**Comment by lightclient** [comment]
@TtheBC01 you're right, thank you.

**Comment by TtheBC01** [comment]
is it ok to just fork the new ERCs repo, add our ERC under the number that was assigned from the EIP repo and create a new PR? or is it preferred to stick to this rebasing procedure?

**Comment by lightclient** [comment]
You can also do that if you prefer.

**Comment by cfries** [comment]
I mentioned this before, but what worked for me was to do everything up to step 7, then, not rebasing, creating a new branch for the PR from ERC master, then chery-picking manually all changes from the EIP pull request branch.

Step 7 did not work because I got conflicts due to the renaming of the folders.

**Comment by Xeway** [comment]
For 8.i., the command that worked for me is `git push origin HEAD:{branch}`

**Comment by 18211308** [comment]
> Член

...

**Comment by 18211308** [comment]
> > член
> 
> ...

?

**Comment by Murshid69** [comment]
Good
