### ISSUE TITLE
MINOR: Broken Doc Link on EIP

### ISSUE THREAD

**Issue by abhik-99** [ethereum/ERCs#83]
### What happened?

In the [EIP-6865 Doc](https://github.com/ethereum/ercs/blob/master/ERCS/erc-6865.md) the link to EIP-712 is broken. It leads to 404 Page. Issue present on master branch.

**Comment by Pandapip1** [comment]
Please submit a PR to fix this. Thank you!

**Comment by abhik-99** [comment]
> Please submit a PR to fix this. Thank you!

https://github.com/ethereum/ERCs/pull/113
